new benchmarker/benchmarks; keeps old benchmarks
orbitdb/ipfs-log pull request #329
Opened 2021-04-26 13:08 UTC by tabcat

adds/updates benchmarks and an npm script to use the new benchmarker.
i decided not the do anything with the old benchmark files yet but we can add that as part of the pr if decided.

related: https://github.com/orbitdb/benchmark-runner/pull/32

2021-05-31 18:55 UTC, aphelionz approved these changes

2021-05-31 18:55 UTC, aphelionz commented on package.json
> +    "orbit-db-benchmark-runner": "github:tabcat/benchmark-runner#benchmarker",
I suppose it's ok to publish a new version of the bechmark runner at this point?

2021-05-31 18:56 UTC, aphelionz requested changes
Whoops, meant to request changes

2021-05-31 21:14 UTC, aphelionz commented on package.json
> +    "orbit-db-benchmark-runner": "github:tabcat/benchmark-runner#benchmarker",
I published `orbit-db-benchmark-runner@2.0.0` so you can use that here.

2021-05-31 23:58 UTC, aphelionz commented
We should probably remove the call to `npm run benchmark` in CI until we have a way to reliably compare performance across builds

2021-06-01 08:35 UTC, tabcat commented
> We should probably remove the call to `npm run benchmark` in CI until we have a way to reliably compare performance across builds

I was unaware it was added; where is it added?

2022-10-06 01:23 UTC, closed without merging